.PHONY: help
help:
	@echo "Targets:"
	@echo "  make api                 Run API (loads ENV_FILE)"
	@echo "  make api-log             Run API + tee to /tmp/api.log"
	@echo "  make check               gofmt + test + vet"
	@echo "  make audit               check + rules: no >100 lines + 1 pkg/dir (+ makefiles <=100)"
	@echo "  make sanity              curl /health /v1/health /ga-ada"
	@echo ""
	@echo "Legacy (Postgres/dev tooling):"
	@echo "  make legacy-dev-up-postgres            Start postgres (docker compose)"
	@echo "  make legacy-dev-down-postgres          Stop postgres"
	@echo "  make legacy-dev-ps-postgres            Show containers"
	@echo "  make legacy-dev-logs-postgres          Tail postgres logs"
	@echo "  make legacy-db-psql-postgres           Open psql (via compose exec)"
	@echo "  make legacy-migrate-status-postgres    Show migration status"
	@echo "  make legacy-migrate-up-postgres        Apply migrations"
	@echo ""
	@echo "Deprecated aliases (still work): dev-up dev-down dev-ps dev-logs db-psql migrate-status migrate-up"
	@echo ""
	@echo "Vars:"
	@echo "  ENV_FILE=.env"
	@echo "  COMPOSE_FILE=deploy/docker/docker-compose.dev.yml"
