.PHONY: help
help:
	@echo "Targets:"
	@echo "  make api                 Run API (loads ENV_FILE)"
	@echo "  make api-log             Run API + tee to /tmp/api.log"
	@echo "  make check               gofmt + test + vet"
	@echo "  make audit               check + rules: no >100 lines + 1 pkg/dir (+ makefiles <=100)"
	@echo "  make sanity              curl /health /v1/health /ga-ada"		  
	@echo ""
	@echo "Legacy (Postgres/dev tooling):"
	@echo "  make legacy-dev-up-postgres            Start postgres (docker compose)"
	@echo "  make legacy-dev-down-postgres          Stop postgres"
	@echo "  make legacy-dev-ps-postgres            Show containers"
	@echo "  make legacy-dev-logs-postgres          Tail postgres logs"
	@echo "  make legacy-db-psql-postgres           Open psql (via compose exec)"
	@echo "  make legacy-migrate-status-postgres    Show migration status"
	@echo "  make legacy-migrate-up-postgres        Apply migrations"
	@echo ""
	@echo "Deprecated aliases (still work): dev-up dev-down dev-ps dev-logs db-psql migrate-status migrate-up"
	@echo ""
	@echo "Vars:"
	@echo "  ENV_FILE=.env"
	@echo "  COMPOSE_FILE=deploy/docker/docker-compose.dev.yml"
	@echo ""
	@echo "AWS Ops (pinned regions):"
	@echo "  make aws-whoami          STS identity (hosting+lambda regions)"
	@echo "  make aws-sqs-list        List queues (hosting region)"
	@echo "  make aws-sqs-attrs       Show main queue attrs (ARN/Redrive/etc)"
	@echo "  make aws-dlq-ensure      Ensure DLQ exists + show DLQ ARN"
	@echo "  make aws-redrive-set     Set RedrivePolicy (MAX_RECEIVE_COUNT)"
	@echo "  make aws-alarms-sqs      Show SQS alarms"
	@echo "  make aws-alarms-lambda   Show Lambda alarm"
	@echo "  make aws-ddb-find-audit  Find/describe audit table in both regions"
	@echo "  make aws-logs-find       Find log group for LAMBDA_WORKER"
